development:
  client_id: <%= Rails.application.credentials.paypal[:id] %>
  client_secret: <%= Rails.application.credentials.paypal[:secret] %>
production:
  client_id: <%= Rails.application.credentials.paypal[:id] %>
  client_secret: <%= Rails.application.credentials.paypal[:secret] %>
